package fr.cesi.atlantismedia.entities;
// Generated 16 janv. 2020 21:29:33 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

// TODO: Auto-generated Javadoc
/**
 * Artiste generated by hbm2java.
 */
public class Artiste implements java.io.Serializable {

	/** The id artiste. */
	private Integer idArtiste;
	
	/** The nom. */
	private String nom;
	
	/** The prenom. */
	private String prenom;
	
	/** The type artistes. */
	private Set typeArtistes = new HashSet(0);
	
	/** The castings. */
	private Set castings = new HashSet(0);

	/**
	 * Instantiates a new artiste.
	 */
	public Artiste() {
	}

	/**
	 * Instantiates a new artiste.
	 *
	 * @param nom the nom
	 */
	public Artiste(String nom) {
		this.nom = nom;
	}

	/**
	 * Instantiates a new artiste.
	 *
	 * @param nom the nom
	 * @param prenom the prenom
	 * @param typeArtistes the type artistes
	 * @param castings the castings
	 */
	public Artiste(String nom, String prenom, Set typeArtistes, Set castings) {
		this.nom = nom;
		this.prenom = prenom;
		this.typeArtistes = typeArtistes;
		this.castings = castings;
	}

	/**
	 * Gets the id artiste.
	 *
	 * @return the id artiste
	 */
	public Integer getIdArtiste() {
		return this.idArtiste;
	}

	/**
	 * Sets the id artiste.
	 *
	 * @param idArtiste the new id artiste
	 */
	public void setIdArtiste(Integer idArtiste) {
		this.idArtiste = idArtiste;
	}

	/**
	 * Gets the nom.
	 *
	 * @return the nom
	 */
	public String getNom() {
		return this.nom;
	}

	/**
	 * Sets the nom.
	 *
	 * @param nom the new nom
	 */
	public void setNom(String nom) {
		this.nom = nom;
	}

	/**
	 * Gets the prenom.
	 *
	 * @return the prenom
	 */
	public String getPrenom() {
		return this.prenom;
	}

	/**
	 * Sets the prenom.
	 *
	 * @param prenom the new prenom
	 */
	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	/**
	 * Gets the type artistes.
	 *
	 * @return the type artistes
	 */
	public Set getTypeArtistes() {
		return this.typeArtistes;
	}

	/**
	 * Sets the type artistes.
	 *
	 * @param typeArtistes the new type artistes
	 */
	public void setTypeArtistes(Set typeArtistes) {
		this.typeArtistes = typeArtistes;
	}

	/**
	 * Gets the castings.
	 *
	 * @return the castings
	 */
	public Set getCastings() {
		return this.castings;
	}

	/**
	 * Sets the castings.
	 *
	 * @param castings the new castings
	 */
	public void setCastings(Set castings) {
		this.castings = castings;
	}

}
