package fr.cesi.atlantismedia.entities;
// Generated 12 janv. 2020 19:04:39 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Artiste generated by hbm2java
 */
public class Artiste implements java.io.Serializable {

	private int idArtiste;
	private String nom;
	private String prenom;
	private Set typeArtistes = new HashSet(0);
	private Set oeuvreArtistes = new HashSet(0);

	public Artiste() {
	}

	public Artiste(int idArtiste, String nom) {
		this.idArtiste = idArtiste;
		this.nom = nom;
	}

	public Artiste(int idArtiste, String nom, String prenom, Set typeArtistes, Set oeuvreArtistes) {
		this.idArtiste = idArtiste;
		this.nom = nom;
		this.prenom = prenom;
		this.typeArtistes = typeArtistes;
		this.oeuvreArtistes = oeuvreArtistes;
	}

	public int getIdArtiste() {
		return this.idArtiste;
	}

	public void setIdArtiste(int idArtiste) {
		this.idArtiste = idArtiste;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public Set getTypeArtistes() {
		return this.typeArtistes;
	}

	public void setTypeArtistes(Set typeArtistes) {
		this.typeArtistes = typeArtistes;
	}

	public Set getOeuvreArtistes() {
		return this.oeuvreArtistes;
	}

	public void setOeuvreArtistes(Set oeuvreArtistes) {
		this.oeuvreArtistes = oeuvreArtistes;
	}

}
