package fr.cesi.atlantismedia.entities;
// Generated 16 janv. 2020 21:29:33 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Categorie generated by hbm2java.
 */
public class Categorie implements java.io.Serializable {

	/** The id categorie. */
	private Integer idCategorie;
	
	/** The libelle. */
	private String libelle;
	
	/** The oeuvres. */
	private Set oeuvres = new HashSet(0);

	/**
	 * Instantiates a new categorie.
	 */
	public Categorie() {
	}

	/**
	 * Instantiates a new categorie.
	 *
	 * @param libelle the libelle
	 */
	public Categorie(String libelle) {
		this.libelle = libelle;
	}

	/**
	 * Instantiates a new categorie.
	 *
	 * @param libelle the libelle
	 * @param oeuvres the oeuvres
	 */
	public Categorie(String libelle, Set oeuvres) {
		this.libelle = libelle;
		this.oeuvres = oeuvres;
	}

	/**
	 * Gets the id categorie.
	 *
	 * @return the id categorie
	 */
	public Integer getIdCategorie() {
		return this.idCategorie;
	}

	/**
	 * Sets the id categorie.
	 *
	 * @param idCategorie the new id categorie
	 */
	public void setIdCategorie(Integer idCategorie) {
		this.idCategorie = idCategorie;
	}

	/**
	 * Gets the libelle.
	 *
	 * @return the libelle
	 */
	public String getLibelle() {
		return this.libelle;
	}

	/**
	 * Sets the libelle.
	 *
	 * @param libelle the new libelle
	 */
	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	/**
	 * Gets the oeuvres.
	 *
	 * @return the oeuvres
	 */
	public Set getOeuvres() {
		return this.oeuvres;
	}

	/**
	 * Sets the oeuvres.
	 *
	 * @param oeuvres the new oeuvres
	 */
	public void setOeuvres(Set oeuvres) {
		this.oeuvres = oeuvres;
	}

}
