package fr.cesi.atlantismedia.entities;
// Generated 16 janv. 2020 21:29:33 by Hibernate Tools 5.4.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Critique generated by hbm2java.
 */
public class Critique implements java.io.Serializable {

	/** The id critique. */
	private Integer idCritique;
	
	/** The commentaire. */
	private String commentaire;
	
	/** The note. */
	private Integer note;
	
	/** The date commentaire. */
	private Date dateCommentaire;
	
	/** The oeuvres. */
	private Set oeuvres = new HashSet(0);

	/**
	 * Instantiates a new critique.
	 */
	public Critique() {
	}

	/**
	 * Instantiates a new critique.
	 *
	 * @param commentaire the commentaire
	 * @param note the note
	 * @param dateCommentaire the date commentaire
	 * @param oeuvres the oeuvres
	 */
	public Critique(String commentaire, Integer note, Date dateCommentaire, Set oeuvres) {
		this.commentaire = commentaire;
		this.note = note;
		this.dateCommentaire = dateCommentaire;
		this.oeuvres = oeuvres;
	}

	/**
	 * Gets the id critique.
	 *
	 * @return the id critique
	 */
	public Integer getIdCritique() {
		return this.idCritique;
	}

	/**
	 * Sets the id critique.
	 *
	 * @param idCritique the new id critique
	 */
	public void setIdCritique(Integer idCritique) {
		this.idCritique = idCritique;
	}

	/**
	 * Gets the commentaire.
	 *
	 * @return the commentaire
	 */
	public String getCommentaire() {
		return this.commentaire;
	}

	/**
	 * Sets the commentaire.
	 *
	 * @param commentaire the new commentaire
	 */
	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	/**
	 * Gets the note.
	 *
	 * @return the note
	 */
	public Integer getNote() {
		return this.note;
	}

	/**
	 * Sets the note.
	 *
	 * @param note the new note
	 */
	public void setNote(Integer note) {
		this.note = note;
	}

	/**
	 * Gets the date commentaire.
	 *
	 * @return the date commentaire
	 */
	public Date getDateCommentaire() {
		return this.dateCommentaire;
	}

	/**
	 * Sets the date commentaire.
	 *
	 * @param dateCommentaire the new date commentaire
	 */
	public void setDateCommentaire(Date dateCommentaire) {
		this.dateCommentaire = dateCommentaire;
	}

	/**
	 * Gets the oeuvres.
	 *
	 * @return the oeuvres
	 */
	public Set getOeuvres() {
		return this.oeuvres;
	}

	/**
	 * Sets the oeuvres.
	 *
	 * @param oeuvres the new oeuvres
	 */
	public void setOeuvres(Set oeuvres) {
		this.oeuvres = oeuvres;
	}

}
