package fr.cesi.atlantismedia.entities;
// Generated 12 janv. 2020 19:04:39 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Genre generated by hbm2java
 */
public class Genre implements java.io.Serializable {

	private int idGenre;
	private String libelle;
	private Set oeuvres = new HashSet(0);

	public Genre() {
	}

	public Genre(int idGenre, String libelle) {
		this.idGenre = idGenre;
		this.libelle = libelle;
	}

	public Genre(int idGenre, String libelle, Set oeuvres) {
		this.idGenre = idGenre;
		this.libelle = libelle;
		this.oeuvres = oeuvres;
	}

	public int getIdGenre() {
		return this.idGenre;
	}

	public void setIdGenre(int idGenre) {
		this.idGenre = idGenre;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set getOeuvres() {
		return this.oeuvres;
	}

	public void setOeuvres(Set oeuvres) {
		this.oeuvres = oeuvres;
	}

}
