package fr.cesi.atlantismedia.entities;
// Generated 16 janv. 2020 21:29:33 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Genre generated by hbm2java.
 */
public class Genre implements java.io.Serializable {

	/** The id genre. */
	private Integer idGenre;
	
	/** The libelle. */
	private String libelle;
	
	/** The oeuvres. */
	private Set oeuvres = new HashSet(0);

	/**
	 * Instantiates a new genre.
	 */
	public Genre() {
	}

	/**
	 * Instantiates a new genre.
	 *
	 * @param libelle the libelle
	 */
	public Genre(String libelle) {
		this.libelle = libelle;
	}

	/**
	 * Instantiates a new genre.
	 *
	 * @param libelle the libelle
	 * @param oeuvres the oeuvres
	 */
	public Genre(String libelle, Set oeuvres) {
		this.libelle = libelle;
		this.oeuvres = oeuvres;
	}

	/**
	 * Gets the id genre.
	 *
	 * @return the id genre
	 */
	public Integer getIdGenre() {
		return this.idGenre;
	}

	/**
	 * Sets the id genre.
	 *
	 * @param idGenre the new id genre
	 */
	public void setIdGenre(Integer idGenre) {
		this.idGenre = idGenre;
	}

	/**
	 * Gets the libelle.
	 *
	 * @return the libelle
	 */
	public String getLibelle() {
		return this.libelle;
	}

	/**
	 * Sets the libelle.
	 *
	 * @param libelle the new libelle
	 */
	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	/**
	 * Gets the oeuvres.
	 *
	 * @return the oeuvres
	 */
	public Set getOeuvres() {
		return this.oeuvres;
	}

	/**
	 * Sets the oeuvres.
	 *
	 * @param oeuvres the new oeuvres
	 */
	public void setOeuvres(Set oeuvres) {
		this.oeuvres = oeuvres;
	}

}
