package fr.cesi.atlantismedia.entities;
// Generated 16 janv. 2020 21:29:33 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Langue generated by hbm2java.
 */
public class Langue implements java.io.Serializable {

	/** The id langue. */
	private Integer idLangue;
	
	/** The libelle. */
	private String libelle;
	
	/** The oeuvres. */
	private Set oeuvres = new HashSet(0);

	/**
	 * Instantiates a new langue.
	 */
	public Langue() {
	}

	/**
	 * Instantiates a new langue.
	 *
	 * @param libelle the libelle
	 */
	public Langue(String libelle) {
		this.libelle = libelle;
	}

	/**
	 * Instantiates a new langue.
	 *
	 * @param libelle the libelle
	 * @param oeuvres the oeuvres
	 */
	public Langue(String libelle, Set oeuvres) {
		this.libelle = libelle;
		this.oeuvres = oeuvres;
	}

	/**
	 * Gets the id langue.
	 *
	 * @return the id langue
	 */
	public Integer getIdLangue() {
		return this.idLangue;
	}

	/**
	 * Sets the id langue.
	 *
	 * @param idLangue the new id langue
	 */
	public void setIdLangue(Integer idLangue) {
		this.idLangue = idLangue;
	}

	/**
	 * Gets the libelle.
	 *
	 * @return the libelle
	 */
	public String getLibelle() {
		return this.libelle;
	}

	/**
	 * Sets the libelle.
	 *
	 * @param libelle the new libelle
	 */
	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	/**
	 * Gets the oeuvres.
	 *
	 * @return the oeuvres
	 */
	public Set getOeuvres() {
		return this.oeuvres;
	}

	/**
	 * Sets the oeuvres.
	 *
	 * @param oeuvres the new oeuvres
	 */
	public void setOeuvres(Set oeuvres) {
		this.oeuvres = oeuvres;
	}

}
