package fr.cesi.atlantismedia.entities;
// Generated 15 janv. 2020 14:02:11 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Morceaux generated by hbm2java
 */
public class Morceaux implements java.io.Serializable {

	private int idMorceaux;
	private String titreMorceaux;
	private String duree;
	private Set oeuvres = new HashSet(0);

	public Morceaux() {
	}

	public Morceaux(int idMorceaux, String titreMorceaux, String duree) {
		this.idMorceaux = idMorceaux;
		this.titreMorceaux = titreMorceaux;
		this.duree = duree;
	}

	public Morceaux(int idMorceaux, String titreMorceaux, String duree, Set oeuvres) {
		this.idMorceaux = idMorceaux;
		this.titreMorceaux = titreMorceaux;
		this.duree = duree;
		this.oeuvres = oeuvres;
	}

	public int getIdMorceaux() {
		return this.idMorceaux;
	}

	public void setIdMorceaux(int idMorceaux) {
		this.idMorceaux = idMorceaux;
	}

	public String getTitreMorceaux() {
		return this.titreMorceaux;
	}

	public void setTitreMorceaux(String titreMorceaux) {
		this.titreMorceaux = titreMorceaux;
	}

	public String getDuree() {
		return this.duree;
	}

	public void setDuree(String duree) {
		this.duree = duree;
	}

	public Set getOeuvres() {
		return this.oeuvres;
	}

	public void setOeuvres(Set oeuvres) {
		this.oeuvres = oeuvres;
	}

}
