package fr.cesi.atlantismedia.entities;
// Generated 16 janv. 2020 21:29:33 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Morceaux generated by hbm2java.
 */
public class Morceaux implements java.io.Serializable {

	/** The id morceaux. */
	private Integer idMorceaux;
	
	/** The titre morceaux. */
	private String titreMorceaux;
	
	/** The duree. */
	private String duree;
	
	/** The oeuvres. */
	private Set oeuvres = new HashSet(0);

	/**
	 * Instantiates a new morceaux.
	 */
	public Morceaux() {
	}

	/**
	 * Instantiates a new morceaux.
	 *
	 * @param titreMorceaux the titre morceaux
	 * @param duree the duree
	 */
	public Morceaux(String titreMorceaux, String duree) {
		this.titreMorceaux = titreMorceaux;
		this.duree = duree;
	}

	/**
	 * Instantiates a new morceaux.
	 *
	 * @param titreMorceaux the titre morceaux
	 * @param duree the duree
	 * @param oeuvres the oeuvres
	 */
	public Morceaux(String titreMorceaux, String duree, Set oeuvres) {
		this.titreMorceaux = titreMorceaux;
		this.duree = duree;
		this.oeuvres = oeuvres;
	}

	/**
	 * Gets the id morceaux.
	 *
	 * @return the id morceaux
	 */
	public Integer getIdMorceaux() {
		return this.idMorceaux;
	}

	/**
	 * Sets the id morceaux.
	 *
	 * @param idMorceaux the new id morceaux
	 */
	public void setIdMorceaux(Integer idMorceaux) {
		this.idMorceaux = idMorceaux;
	}

	/**
	 * Gets the titre morceaux.
	 *
	 * @return the titre morceaux
	 */
	public String getTitreMorceaux() {
		return this.titreMorceaux;
	}

	/**
	 * Sets the titre morceaux.
	 *
	 * @param titreMorceaux the new titre morceaux
	 */
	public void setTitreMorceaux(String titreMorceaux) {
		this.titreMorceaux = titreMorceaux;
	}

	/**
	 * Gets the duree.
	 *
	 * @return the duree
	 */
	public String getDuree() {
		return this.duree;
	}

	/**
	 * Sets the duree.
	 *
	 * @param duree the new duree
	 */
	public void setDuree(String duree) {
		this.duree = duree;
	}

	/**
	 * Gets the oeuvres.
	 *
	 * @return the oeuvres
	 */
	public Set getOeuvres() {
		return this.oeuvres;
	}

	/**
	 * Sets the oeuvres.
	 *
	 * @param oeuvres the new oeuvres
	 */
	public void setOeuvres(Set oeuvres) {
		this.oeuvres = oeuvres;
	}

}
