package fr.cesi.atlantismedia.entities;
// Generated 15 janv. 2020 14:02:11 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * OeuvreCritique generated by hbm2java
 */
public class OeuvreCritique implements java.io.Serializable {

	private OeuvreCritiqueId id;
	private Critique critique;
	private Oeuvre oeuvre;
	private Date dateDeCommentaire;

	public OeuvreCritique() {
	}

	public OeuvreCritique(OeuvreCritiqueId id, Critique critique, Oeuvre oeuvre) {
		this.id = id;
		this.critique = critique;
		this.oeuvre = oeuvre;
	}

	public OeuvreCritique(OeuvreCritiqueId id, Critique critique, Oeuvre oeuvre, Date dateDeCommentaire) {
		this.id = id;
		this.critique = critique;
		this.oeuvre = oeuvre;
		this.dateDeCommentaire = dateDeCommentaire;
	}

	public OeuvreCritiqueId getId() {
		return this.id;
	}

	public void setId(OeuvreCritiqueId id) {
		this.id = id;
	}

	public Critique getCritique() {
		return this.critique;
	}

	public void setCritique(Critique critique) {
		this.critique = critique;
	}

	public Oeuvre getOeuvre() {
		return this.oeuvre;
	}

	public void setOeuvre(Oeuvre oeuvre) {
		this.oeuvre = oeuvre;
	}

	public Date getDateDeCommentaire() {
		return this.dateDeCommentaire;
	}

	public void setDateDeCommentaire(Date dateDeCommentaire) {
		this.dateDeCommentaire = dateDeCommentaire;
	}

}
