package fr.cesi.atlantismedia.entities;
// Generated 16 janv. 2020 21:29:33 by Hibernate Tools 5.4.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Oeuvre generated by hbm2java.
 */
public class Oeuvre implements java.io.Serializable {

	/** The id oeuvre. */
	private Integer idOeuvre;
	
	/** The categorie. */
	private Categorie categorie;
	
	/** The origine. */
	private Origine origine;
	
	/** The statut. */
	private Statut statut;
	
	/** The support. */
	private Support support;
	
	/** The titre. */
	private String titre;
	
	/** The duree. */
	private String duree;
	
	/** The code isbn. */
	private String codeIsbn;
	
	/** The date acquisition. */
	private Date dateAcquisition;
	
	/** The date realisation. */
	private Date dateRealisation;
	
	/** The castings. */
	private Set castings = new HashSet(0);
	
	/** The genres. */
	private Set genres = new HashSet(0);
	
	/** The critiques. */
	private Set critiques = new HashSet(0);
	
	/** The langues. */
	private Set langues = new HashSet(0);
	
	/** The morceauxes. */
	private Set morceauxes = new HashSet(0);

	/**
	 * Instantiates a new oeuvre.
	 */
	public Oeuvre() {
	}

	/**
	 * Instantiates a new oeuvre.
	 *
	 * @param categorie the categorie
	 * @param origine the origine
	 * @param statut the statut
	 * @param support the support
	 * @param titre the titre
	 */
	public Oeuvre(Categorie categorie, Origine origine, Statut statut, Support support, String titre) {
		this.categorie = categorie;
		this.origine = origine;
		this.statut = statut;
		this.support = support;
		this.titre = titre;
	}

	/**
	 * Instantiates a new oeuvre.
	 *
	 * @param categorie the categorie
	 * @param origine the origine
	 * @param statut the statut
	 * @param support the support
	 * @param titre the titre
	 * @param duree the duree
	 * @param codeIsbn the code isbn
	 * @param dateAcquisition the date acquisition
	 * @param dateRealisation the date realisation
	 * @param castings the castings
	 * @param genres the genres
	 * @param critiques the critiques
	 * @param langues the langues
	 * @param morceauxes the morceauxes
	 */
	public Oeuvre(Categorie categorie, Origine origine, Statut statut, Support support, String titre, String duree,
			String codeIsbn, Date dateAcquisition, Date dateRealisation, Set castings, Set genres, Set critiques,
			Set langues, Set morceauxes) {
		this.categorie = categorie;
		this.origine = origine;
		this.statut = statut;
		this.support = support;
		this.titre = titre;
		this.duree = duree;
		this.codeIsbn = codeIsbn;
		this.dateAcquisition = dateAcquisition;
		this.dateRealisation = dateRealisation;
		this.castings = castings;
		this.genres = genres;
		this.critiques = critiques;
		this.langues = langues;
		this.morceauxes = morceauxes;
	}

	/**
	 * Gets the id oeuvre.
	 *
	 * @return the id oeuvre
	 */
	public Integer getIdOeuvre() {
		return this.idOeuvre;
	}

	/**
	 * Sets the id oeuvre.
	 *
	 * @param idOeuvre the new id oeuvre
	 */
	public void setIdOeuvre(Integer idOeuvre) {
		this.idOeuvre = idOeuvre;
	}

	/**
	 * Gets the categorie.
	 *
	 * @return the categorie
	 */
	public Categorie getCategorie() {
		return this.categorie;
	}

	/**
	 * Sets the categorie.
	 *
	 * @param categorie the new categorie
	 */
	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	/**
	 * Gets the origine.
	 *
	 * @return the origine
	 */
	public Origine getOrigine() {
		return this.origine;
	}

	/**
	 * Sets the origine.
	 *
	 * @param origine the new origine
	 */
	public void setOrigine(Origine origine) {
		this.origine = origine;
	}

	/**
	 * Gets the statut.
	 *
	 * @return the statut
	 */
	public Statut getStatut() {
		return this.statut;
	}

	/**
	 * Sets the statut.
	 *
	 * @param statut the new statut
	 */
	public void setStatut(Statut statut) {
		this.statut = statut;
	}

	/**
	 * Gets the support.
	 *
	 * @return the support
	 */
	public Support getSupport() {
		return this.support;
	}

	/**
	 * Sets the support.
	 *
	 * @param support the new support
	 */
	public void setSupport(Support support) {
		this.support = support;
	}

	/**
	 * Gets the titre.
	 *
	 * @return the titre
	 */
	public String getTitre() {
		return this.titre;
	}

	/**
	 * Sets the titre.
	 *
	 * @param titre the new titre
	 */
	public void setTitre(String titre) {
		this.titre = titre;
	}

	/**
	 * Gets the duree.
	 *
	 * @return the duree
	 */
	public String getDuree() {
		return this.duree;
	}

	/**
	 * Sets the duree.
	 *
	 * @param duree the new duree
	 */
	public void setDuree(String duree) {
		this.duree = duree;
	}

	/**
	 * Gets the code isbn.
	 *
	 * @return the code isbn
	 */
	public String getCodeIsbn() {
		return this.codeIsbn;
	}

	/**
	 * Sets the code isbn.
	 *
	 * @param codeIsbn the new code isbn
	 */
	public void setCodeIsbn(String codeIsbn) {
		this.codeIsbn = codeIsbn;
	}

	/**
	 * Gets the date acquisition.
	 *
	 * @return the date acquisition
	 */
	public Date getDateAcquisition() {
		return this.dateAcquisition;
	}

	/**
	 * Sets the date acquisition.
	 *
	 * @param dateAcquisition the new date acquisition
	 */
	public void setDateAcquisition(Date dateAcquisition) {
		this.dateAcquisition = dateAcquisition;
	}

	/**
	 * Gets the date realisation.
	 *
	 * @return the date realisation
	 */
	public Date getDateRealisation() {
		return this.dateRealisation;
	}

	/**
	 * Sets the date realisation.
	 *
	 * @param dateRealisation the new date realisation
	 */
	public void setDateRealisation(Date dateRealisation) {
		this.dateRealisation = dateRealisation;
	}

	/**
	 * Gets the castings.
	 *
	 * @return the castings
	 */
	public Set getCastings() {
		return this.castings;
	}

	/**
	 * Sets the castings.
	 *
	 * @param castings the new castings
	 */
	public void setCastings(Set castings) {
		this.castings = castings;
	}

	/**
	 * Gets the genres.
	 *
	 * @return the genres
	 */
	public Set getGenres() {
		return this.genres;
	}

	/**
	 * Sets the genres.
	 *
	 * @param genres the new genres
	 */
	public void setGenres(Set genres) {
		this.genres = genres;
	}

	/**
	 * Gets the critiques.
	 *
	 * @return the critiques
	 */
	public Set getCritiques() {
		return this.critiques;
	}

	/**
	 * Sets the critiques.
	 *
	 * @param critiques the new critiques
	 */
	public void setCritiques(Set critiques) {
		this.critiques = critiques;
	}

	/**
	 * Gets the langues.
	 *
	 * @return the langues
	 */
	public Set getLangues() {
		return this.langues;
	}

	/**
	 * Sets the langues.
	 *
	 * @param langues the new langues
	 */
	public void setLangues(Set langues) {
		this.langues = langues;
	}

	/**
	 * Gets the morceauxes.
	 *
	 * @return the morceauxes
	 */
	public Set getMorceauxes() {
		return this.morceauxes;
	}

	/**
	 * Sets the morceauxes.
	 *
	 * @param morceauxes the new morceauxes
	 */
	public void setMorceauxes(Set morceauxes) {
		this.morceauxes = morceauxes;
	}

}
