package fr.cesi.atlantismedia.entities;
// Generated 12 janv. 2020 19:04:39 by Hibernate Tools 5.4.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Oeuvre generated by hbm2java
 */
public class Oeuvre implements java.io.Serializable {

	private int idOeuvre;
	private Categorie categorie;
	private Origine origine;
	private Statut statut;
	private Support support;
	private String titre;
	private Integer duree;
	private String codeIsbn;
	private Date dateAcquisition;
	private Set genres = new HashSet(0);
	private Set oeuvreArtistes = new HashSet(0);
	private Set oeuvreCritiques = new HashSet(0);
	private Set langues = new HashSet(0);
	private Set morceauxes = new HashSet(0);

	public Oeuvre() {
	}

	public Oeuvre(int idOeuvre, Categorie categorie, Origine origine, Statut statut, Support support, String titre) {
		this.idOeuvre = idOeuvre;
		this.categorie = categorie;
		this.origine = origine;
		this.statut = statut;
		this.support = support;
		this.titre = titre;
	}

	public Oeuvre(int idOeuvre, Categorie categorie, Origine origine, Statut statut, Support support, String titre,
			Integer duree, String codeIsbn, Date dateAcquisition, Set genres, Set oeuvreArtistes, Set oeuvreCritiques,
			Set langues, Set morceauxes) {
		this.idOeuvre = idOeuvre;
		this.categorie = categorie;
		this.origine = origine;
		this.statut = statut;
		this.support = support;
		this.titre = titre;
		this.duree = duree;
		this.codeIsbn = codeIsbn;
		this.dateAcquisition = dateAcquisition;
		this.genres = genres;
		this.oeuvreArtistes = oeuvreArtistes;
		this.oeuvreCritiques = oeuvreCritiques;
		this.langues = langues;
		this.morceauxes = morceauxes;
	}

	public int getIdOeuvre() {
		return this.idOeuvre;
	}

	public void setIdOeuvre(int idOeuvre) {
		this.idOeuvre = idOeuvre;
	}

	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	public Origine getOrigine() {
		return this.origine;
	}

	public void setOrigine(Origine origine) {
		this.origine = origine;
	}

	public Statut getStatut() {
		return this.statut;
	}

	public void setStatut(Statut statut) {
		this.statut = statut;
	}

	public Support getSupport() {
		return this.support;
	}

	public void setSupport(Support support) {
		this.support = support;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public Integer getDuree() {
		return this.duree;
	}

	public void setDuree(Integer duree) {
		this.duree = duree;
	}

	public String getCodeIsbn() {
		return this.codeIsbn;
	}

	public void setCodeIsbn(String codeIsbn) {
		this.codeIsbn = codeIsbn;
	}

	public Date getDateAcquisition() {
		return this.dateAcquisition;
	}

	public void setDateAcquisition(Date dateAcquisition) {
		this.dateAcquisition = dateAcquisition;
	}

	public Set getGenres() {
		return this.genres;
	}

	public void setGenres(Set genres) {
		this.genres = genres;
	}

	public Set getOeuvreArtistes() {
		return this.oeuvreArtistes;
	}

	public void setOeuvreArtistes(Set oeuvreArtistes) {
		this.oeuvreArtistes = oeuvreArtistes;
	}

	public Set getOeuvreCritiques() {
		return this.oeuvreCritiques;
	}

	public void setOeuvreCritiques(Set oeuvreCritiques) {
		this.oeuvreCritiques = oeuvreCritiques;
	}

	public Set getLangues() {
		return this.langues;
	}

	public void setLangues(Set langues) {
		this.langues = langues;
	}

	public Set getMorceauxes() {
		return this.morceauxes;
	}

	public void setMorceauxes(Set morceauxes) {
		this.morceauxes = morceauxes;
	}

}
