package fr.cesi.atlantismedia.entities;
// Generated 12 janv. 2020 19:04:39 by Hibernate Tools 5.4.7.Final

/**
 * OeuvreArtiste generated by hbm2java
 */
public class OeuvreArtiste implements java.io.Serializable {

	private OeuvreArtisteId id;
	private Artiste artiste;
	private Oeuvre oeuvre;
	private String dateDeRealisation;

	public OeuvreArtiste() {
	}

	public OeuvreArtiste(OeuvreArtisteId id, Artiste artiste, Oeuvre oeuvre) {
		this.id = id;
		this.artiste = artiste;
		this.oeuvre = oeuvre;
	}

	public OeuvreArtiste(OeuvreArtisteId id, Artiste artiste, Oeuvre oeuvre, String dateDeRealisation) {
		this.id = id;
		this.artiste = artiste;
		this.oeuvre = oeuvre;
		this.dateDeRealisation = dateDeRealisation;
	}

	public OeuvreArtisteId getId() {
		return this.id;
	}

	public void setId(OeuvreArtisteId id) {
		this.id = id;
	}

	public Artiste getArtiste() {
		return this.artiste;
	}

	public void setArtiste(Artiste artiste) {
		this.artiste = artiste;
	}

	public Oeuvre getOeuvre() {
		return this.oeuvre;
	}

	public void setOeuvre(Oeuvre oeuvre) {
		this.oeuvre = oeuvre;
	}

	public String getDateDeRealisation() {
		return this.dateDeRealisation;
	}

	public void setDateDeRealisation(String dateDeRealisation) {
		this.dateDeRealisation = dateDeRealisation;
	}

}
