package fr.cesi.atlantismedia.entities;
// Generated 12 janv. 2020 19:04:39 by Hibernate Tools 5.4.7.Final

/**
 * OeuvreCritiqueId generated by hbm2java
 */
public class OeuvreCritiqueId implements java.io.Serializable {

	private int idOeuvre;
	private int idCritique;

	public OeuvreCritiqueId() {
	}

	public OeuvreCritiqueId(int idOeuvre, int idCritique) {
		this.idOeuvre = idOeuvre;
		this.idCritique = idCritique;
	}

	public int getIdOeuvre() {
		return this.idOeuvre;
	}

	public void setIdOeuvre(int idOeuvre) {
		this.idOeuvre = idOeuvre;
	}

	public int getIdCritique() {
		return this.idCritique;
	}

	public void setIdCritique(int idCritique) {
		this.idCritique = idCritique;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OeuvreCritiqueId))
			return false;
		OeuvreCritiqueId castOther = (OeuvreCritiqueId) other;

		return (this.getIdOeuvre() == castOther.getIdOeuvre()) && (this.getIdCritique() == castOther.getIdCritique());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdOeuvre();
		result = 37 * result + this.getIdCritique();
		return result;
	}

}
