package fr.cesi.atlantismedia.entities;
// Generated 16 janv. 2020 21:29:33 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Origine generated by hbm2java.
 */
public class Origine implements java.io.Serializable {

	/** The id origine. */
	private Integer idOrigine;
	
	/** The libelle. */
	private String libelle;
	
	/** The oeuvres. */
	private Set oeuvres = new HashSet(0);

	/**
	 * Instantiates a new origine.
	 */
	public Origine() {
	}

	/**
	 * Instantiates a new origine.
	 *
	 * @param libelle the libelle
	 * @param oeuvres the oeuvres
	 */
	public Origine(String libelle, Set oeuvres) {
		this.libelle = libelle;
		this.oeuvres = oeuvres;
	}

	/**
	 * Gets the id origine.
	 *
	 * @return the id origine
	 */
	public Integer getIdOrigine() {
		return this.idOrigine;
	}

	/**
	 * Sets the id origine.
	 *
	 * @param idOrigine the new id origine
	 */
	public void setIdOrigine(Integer idOrigine) {
		this.idOrigine = idOrigine;
	}

	/**
	 * Gets the libelle.
	 *
	 * @return the libelle
	 */
	public String getLibelle() {
		return this.libelle;
	}

	/**
	 * Sets the libelle.
	 *
	 * @param libelle the new libelle
	 */
	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	/**
	 * Gets the oeuvres.
	 *
	 * @return the oeuvres
	 */
	public Set getOeuvres() {
		return this.oeuvres;
	}

	/**
	 * Sets the oeuvres.
	 *
	 * @param oeuvres the new oeuvres
	 */
	public void setOeuvres(Set oeuvres) {
		this.oeuvres = oeuvres;
	}

}
