package fr.cesi.atlantismedia.entities;
// Generated 15 janv. 2020 14:02:11 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Origine generated by hbm2java
 */
public class Origine implements java.io.Serializable {

	private int idOrigine;
	private String libelle;
	private Set oeuvres = new HashSet(0);

	public Origine() {
	}

	public Origine(int idOrigine) {
		this.idOrigine = idOrigine;
	}

	public Origine(int idOrigine, String libelle, Set oeuvres) {
		this.idOrigine = idOrigine;
		this.libelle = libelle;
		this.oeuvres = oeuvres;
	}

	public int getIdOrigine() {
		return this.idOrigine;
	}

	public void setIdOrigine(int idOrigine) {
		this.idOrigine = idOrigine;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set getOeuvres() {
		return this.oeuvres;
	}

	public void setOeuvres(Set oeuvres) {
		this.oeuvres = oeuvres;
	}

}
