package fr.cesi.atlantismedia.entities;
// Generated 16 janv. 2020 21:29:33 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Statut generated by hbm2java.
 */
public class Statut implements java.io.Serializable {

	/** The id statut. */
	private Integer idStatut;
	
	/** The libelle. */
	private String libelle;
	
	/** The oeuvres. */
	private Set oeuvres = new HashSet(0);

	/**
	 * Instantiates a new statut.
	 */
	public Statut() {
	}

	/**
	 * Instantiates a new statut.
	 *
	 * @param libelle the libelle
	 * @param oeuvres the oeuvres
	 */
	public Statut(String libelle, Set oeuvres) {
		this.libelle = libelle;
		this.oeuvres = oeuvres;
	}

	/**
	 * Gets the id statut.
	 *
	 * @return the id statut
	 */
	public Integer getIdStatut() {
		return this.idStatut;
	}

	/**
	 * Sets the id statut.
	 *
	 * @param idStatut the new id statut
	 */
	public void setIdStatut(Integer idStatut) {
		this.idStatut = idStatut;
	}

	/**
	 * Gets the libelle.
	 *
	 * @return the libelle
	 */
	public String getLibelle() {
		return this.libelle;
	}

	/**
	 * Sets the libelle.
	 *
	 * @param libelle the new libelle
	 */
	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	/**
	 * Gets the oeuvres.
	 *
	 * @return the oeuvres
	 */
	public Set getOeuvres() {
		return this.oeuvres;
	}

	/**
	 * Sets the oeuvres.
	 *
	 * @param oeuvres the new oeuvres
	 */
	public void setOeuvres(Set oeuvres) {
		this.oeuvres = oeuvres;
	}

}
