package fr.cesi.atlantismedia.entities;
// Generated 16 janv. 2020 21:29:33 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Support generated by hbm2java.
 */
public class Support implements java.io.Serializable {

	/** The id support. */
	private Integer idSupport;
	
	/** The libelle. */
	private String libelle;
	
	/** The oeuvres. */
	private Set oeuvres = new HashSet(0);

	/**
	 * Instantiates a new support.
	 */
	public Support() {
	}

	/**
	 * Instantiates a new support.
	 *
	 * @param libelle the libelle
	 */
	public Support(String libelle) {
		this.libelle = libelle;
	}

	/**
	 * Instantiates a new support.
	 *
	 * @param libelle the libelle
	 * @param oeuvres the oeuvres
	 */
	public Support(String libelle, Set oeuvres) {
		this.libelle = libelle;
		this.oeuvres = oeuvres;
	}

	/**
	 * Gets the id support.
	 *
	 * @return the id support
	 */
	public Integer getIdSupport() {
		return this.idSupport;
	}

	/**
	 * Sets the id support.
	 *
	 * @param idSupport the new id support
	 */
	public void setIdSupport(Integer idSupport) {
		this.idSupport = idSupport;
	}

	/**
	 * Gets the libelle.
	 *
	 * @return the libelle
	 */
	public String getLibelle() {
		return this.libelle;
	}

	/**
	 * Sets the libelle.
	 *
	 * @param libelle the new libelle
	 */
	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	/**
	 * Gets the oeuvres.
	 *
	 * @return the oeuvres
	 */
	public Set getOeuvres() {
		return this.oeuvres;
	}

	/**
	 * Sets the oeuvres.
	 *
	 * @param oeuvres the new oeuvres
	 */
	public void setOeuvres(Set oeuvres) {
		this.oeuvres = oeuvres;
	}

}
