package fr.cesi.atlantismedia.entities;
// Generated 12 janv. 2020 19:04:39 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TypeArtiste generated by hbm2java
 */
public class TypeArtiste implements java.io.Serializable {

	private int idTypeArtiste;
	private String libelle;
	private Set artistes = new HashSet(0);

	public TypeArtiste() {
	}

	public TypeArtiste(int idTypeArtiste) {
		this.idTypeArtiste = idTypeArtiste;
	}

	public TypeArtiste(int idTypeArtiste, String libelle, Set artistes) {
		this.idTypeArtiste = idTypeArtiste;
		this.libelle = libelle;
		this.artistes = artistes;
	}

	public int getIdTypeArtiste() {
		return this.idTypeArtiste;
	}

	public void setIdTypeArtiste(int idTypeArtiste) {
		this.idTypeArtiste = idTypeArtiste;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set getArtistes() {
		return this.artistes;
	}

	public void setArtistes(Set artistes) {
		this.artistes = artistes;
	}

}
