package fr.cesi.atlantismedia.entities;
// Generated 16 janv. 2020 21:29:33 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TypeArtiste generated by hbm2java.
 */
public class TypeArtiste implements java.io.Serializable {

	/** The id type artiste. */
	private Integer idTypeArtiste;
	
	/** The libelle. */
	private String libelle;
	
	/** The artistes. */
	private Set artistes = new HashSet(0);

	/**
	 * Instantiates a new type artiste.
	 */
	public TypeArtiste() {
	}

	/**
	 * Instantiates a new type artiste.
	 *
	 * @param libelle the libelle
	 * @param artistes the artistes
	 */
	public TypeArtiste(String libelle, Set artistes) {
		this.libelle = libelle;
		this.artistes = artistes;
	}

	/**
	 * Gets the id type artiste.
	 *
	 * @return the id type artiste
	 */
	public Integer getIdTypeArtiste() {
		return this.idTypeArtiste;
	}

	/**
	 * Sets the id type artiste.
	 *
	 * @param idTypeArtiste the new id type artiste
	 */
	public void setIdTypeArtiste(Integer idTypeArtiste) {
		this.idTypeArtiste = idTypeArtiste;
	}

	/**
	 * Gets the libelle.
	 *
	 * @return the libelle
	 */
	public String getLibelle() {
		return this.libelle;
	}

	/**
	 * Sets the libelle.
	 *
	 * @param libelle the new libelle
	 */
	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	/**
	 * Gets the artistes.
	 *
	 * @return the artistes
	 */
	public Set getArtistes() {
		return this.artistes;
	}

	/**
	 * Sets the artistes.
	 *
	 * @param artistes the new artistes
	 */
	public void setArtistes(Set artistes) {
		this.artistes = artistes;
	}

}
